// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestDefaultCaseRule(t *testing.T) {
	RunRuleTester(t, "{}", "default-case", []ValidTestCase{
		{Code: `switch (a) { case 1: break; default: break; }`},
		{Code: `switch (a) { case 1: break; case 2: default: break; }`},
		{Code: `switch (a) { case 1: break; default: break; 
 //no default 
 }`},
		{Code: `switch (a) { 
    case 1: break; 

//oh-oh 
 // no default
 }`},
		{Code: `switch (a) { 
    case 1: 

// no default
 }`},
		{Code: `switch (a) { 
    case 1: 

// No default
 }`},
		{Code: `switch (a) { 
    case 1: 

// no deFAUlt
 }`},
		{Code: `switch (a) { 
    case 1: 

// NO DEFAULT
 }`},
		{Code: `switch (a) { 
    case 1: a = 4; 

// no default
 }`},
		{Code: `switch (a) { 
    case 1: a = 4; 

/* no default */
 }`},
		{Code: `switch (a) { 
    case 1: a = 4; break; break; 

// no default
 }`},
		{Code: `switch (a) { // no default
 }`},
		{Code: `switch (a) { }`},
		{
			Code:    `switch (a) { case 1: break; default: break; }`,
			Options: "[{\"commentPattern\":\"default case omitted\"}]",
		},
		{
			Code: `switch (a) { case 1: break; 
 // skip default case 
 }`,
			Options: "[{\"commentPattern\":\"^skip default\"}]",
		},
		{
			Code: `switch (a) { case 1: break; 
 /*
TODO:
 throw error in default case
*/ 
 }`,
			Options: "[{\"commentPattern\":\"default\"}]",
		},
		{
			Code: `switch (a) { case 1: break; 
// 
 }`,
			Options: "[{\"commentPattern\":\".?\"}]",
		},
	}, []InvalidTestCase{
		{
			Code: `switch (a) { case 1: break; }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingDefaultCase",
				},
			},
		},
		{
			Code: `switch (a) { 
 // no default 
 case 1: break;  }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingDefaultCase",
				},
			},
		},
		{
			Code: `switch (a) { case 1: break; 
 // no default 
 // nope 
  }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingDefaultCase",
				},
			},
		},
		{
			Code: `switch (a) { case 1: break; 
 // no default 
 }`,
			Options: "[{\"commentPattern\":\"skipped default case\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingDefaultCase",
				},
			},
		},
		{
			Code: `switch (a) {
case 1: break; 
// default omitted intentionally 
// TODO: add default case 
}`,
			Options: "[{\"commentPattern\":\"default omitted\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingDefaultCase",
				},
			},
		},
		{
			Code: `switch (a) {
case 1: break;
}`,
			Options: "[{\"commentPattern\":\".?\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingDefaultCase",
				},
			},
		},
	})
}
