// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoCallerRule(t *testing.T) {
	RunRuleTester(t, "{}", "no-caller", []ValidTestCase{
		{Code: `var x = arguments.length`},
		{Code: `var x = arguments`},
		{Code: `var x = arguments[0]`},
		{Code: `var x = arguments[caller]`},
	}, []InvalidTestCase{
		{
			Code: `var x = arguments.callee`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
		{
			Code: `var x = arguments.caller`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
	})
}
