// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoExAssignRule(t *testing.T) {
	RunRuleTester(t, "{}", "no-ex-assign", []ValidTestCase{
		{Code: `try { } catch (e) { three = 2 + 1; }`},
		{
			Code:            `try { } catch ({e}) { this.something = 2; }`,
			LanguageOptions: "{\"ecmaVersion\":6}",
		},
		{Code: `function foo() { try { } catch (e) { return false; } }`},
	}, []InvalidTestCase{
		{
			Code: `try { } catch (e) { e = 10; }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
		{
			Code: `try { } catch (ex) { ex = 10; }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
		{
			Code:            `try { } catch (ex) { [ex] = []; }`,
			LanguageOptions: "{\"ecmaVersion\":6}",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
		{
			Code:            `try { } catch (ex) { ({x: ex = 0} = {}); }`,
			LanguageOptions: "{\"ecmaVersion\":6}",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
		{
			Code:            `try { } catch ({message}) { message = 10; }`,
			LanguageOptions: "{\"ecmaVersion\":6}",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpected",
				},
			},
		},
	})
}
