// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoFloatingDecimalRule(t *testing.T) {
	RunRuleTester(t, "{}", "no-floating-decimal", []ValidTestCase{
		{Code: `var x = 2.5;`},
		{Code: `var x = "2.5";`},
	}, []InvalidTestCase{
		{
			Code:   `var x = .5;`,
			Output: `var x = 0.5;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "leading",
				},
			},
		},
		{
			Code:   `var x = -.5;`,
			Output: `var x = -0.5;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "leading",
				},
			},
		},
		{
			Code:   `var x = 2.;`,
			Output: `var x = 2.0;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "trailing",
				},
			},
		},
		{
			Code:   `var x = -2.;`,
			Output: `var x = -2.0;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "trailing",
				},
			},
		},
		{
			Code:   `typeof.2`,
			Output: `typeof 0.2`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "leading",
				},
			},
		},
		{
			Code:            `for(foo of.2);`,
			Output:          `for(foo of 0.2);`,
			LanguageOptions: "{\"ecmaVersion\":2015}",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "leading",
				},
			},
		},
	})
}
