// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoInlineCommentsRule(t *testing.T) {
	RunRuleTester(t, "{\"languageOptions\":{\"ecmaVersion\":5,\"sourceType\":\"script\",\"parserOptions\":{\"ecmaFeatures\":{\"jsx\":true}}}}", "no-inline-comments", []ValidTestCase{
		{Code: `// A valid comment before code
var a = 1;`},
		{Code: `var a = 2;
// A valid comment after code`},
		{Code: `// A solitary comment`},
		{Code: `var a = 1; // eslint-disable-line no-debugger`},
		{Code: `var a = 1; /* eslint-disable-line no-debugger */`},
		{Code: `foo(); /* global foo */`},
		{Code: `foo(); /* globals foo */`},
		{Code: `var foo; /* exported foo */`},
		{Code: `var a = (
            <div>
            {/*comment*/}
            </div>
        )`},
		{Code: `var a = (
            <div>
            { /* comment */ }
            <h1>Some heading</h1>
            </div>
        )`},
		{Code: `var a = (
            <div>
            {// comment
            }
            </div>
        )`},
		{Code: `var a = (
            <div>
            { // comment
            }
            </div>
        )`},
		{Code: `var a = (
            <div>
            {/* comment 1 */
            /* comment 2 */}
            </div>
        )`},
		{Code: `var a = (
            <div>
            {/*
              * comment 1
              */
             /*
              * comment 2
              */}
            </div>
        )`},
		{Code: `var a = (
            <div>
            {/*
               multi
               line
               comment
            */}
            </div>
        )`},
		{
			Code:            `import(/* webpackChunkName: "my-chunk-name" */ './locale/en');`,
			Options:         "[{\"ignorePattern\":\"(?:webpackChunkName):\\\\s.+\"}]",
			LanguageOptions: "{\"ecmaVersion\":2020}",
		},
		{
			Code:    `var foo = 2; // Note: This comment is legal.`,
			Options: "[{\"ignorePattern\":\"Note: \"}]",
		},
	}, []InvalidTestCase{
		{
			Code: `var a = 1; /*A block comment inline after code*/`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `/*A block comment inline before code*/ var a = 2;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code:    `/* something */ var a = 2;`,
			Options: "[{\"ignorePattern\":\"otherthing\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = 3; //A comment inline with code`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = 3; // someday use eslint-disable-line here`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code:    `var a = 3; // other line comment`,
			Options: "[{\"ignorePattern\":\"something\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = 4;
/**A
 * block
 * comment
 * inline
 * between
 * code*/ var foo = a;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = 
{/**/}`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>{/* comment */}</div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>{// comment
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>{/* comment */
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>{/*
                       * comment
                       */
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>{/*
                       * comment
                       */}
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>{/*
                       * comment
                       */}</div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {/*
                  * comment
                  */}</div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                 /*
                  * comment
                  */}</div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                /* comment */}</div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {b/* comment */}
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {/* comment */b}
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {// comment
                    b
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {/* comment */
                    b
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {/*
                  * comment
                  */
                    b
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    b// comment
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    /* comment */b
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    b/* comment */
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    b
                /*
                 * comment
                 */}
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    b
                /* comment */}
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    { /* this is an empty object literal, not braces for js code! */ }
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    {// comment
                    }
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    {
                    /* comment */}
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                { /* two comments on the same line... */ /* ...are not allowed, same as with a non-JSX code */}
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
		{
			Code: `var a = (
                <div>
                {
                    /* overlapping
                    */ /*
                       lines */
                }
                </div>
            )`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "unexpectedInlineComment",
				},
				{
					MessageId: "unexpectedInlineComment",
				},
			},
		},
	})
}
