// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoLossOfPrecisionRule(t *testing.T) {
	RunRuleTester(t, "{\"languageOptions\":{\"parser\":{\"version\":\"8.30.1\",\"meta\":{\"name\":\"typescript-eslint/parser\",\"version\":\"8.30.1\"}}}}", "no-loss-of-precision", []ValidTestCase{
		{Code: `const x = 12345;`},
		{Code: `const x = 123.456;`},
		{Code: `const x = -123.456;`},
		{Code: `const x = 123_456;`},
		{Code: `const x = 123_00_000_000_000_000_000_000_000;`},
		{Code: `const x = 123.000_000_000_000_000_000_000_0;`},
	}, []InvalidTestCase{
		{
			Code: `const x = 9007199254740993;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noLossOfPrecision",
				},
			},
		},
		{
			Code: `const x = 9_007_199_254_740_993;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noLossOfPrecision",
				},
			},
		},
		{
			Code: `const x = 9_007_199_254_740.993e3;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noLossOfPrecision",
				},
			},
		},
		{
			Code: `const x = 0b100_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_001;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noLossOfPrecision",
				},
			},
		},
	})
}
