// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoNewRule(t *testing.T) {
	RunRuleTester(t, "{}", "no-new", []ValidTestCase{
		{Code: `var a = new Date()`},
		{Code: `var a; if (a === new Date()) { a = false; }`},
	}, []InvalidTestCase{
		{
			Code: `new Date()`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noNewStatement",
				},
			},
		},
	})
}
