// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoOctalRule(t *testing.T) {
	RunRuleTester(t, "{\"languageOptions\":{\"ecmaVersion\":5,\"sourceType\":\"script\"}}", "no-octal", []ValidTestCase{
		{Code: `var a = 'hello world';`},
		{Code: `0x1234`},
		{Code: `0X5;`},
		{Code: `a = 0;`},
		{Code: `0.1`},
		{Code: `0.5e1`},
	}, []InvalidTestCase{
		{
			Code: `var a = 01234;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `a = 1 + 01234;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `00`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `08`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `09.1`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `09e1`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `09.1e1`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `018`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `019.1`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `019e1`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
		{
			Code: `019.1e1`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noOctal",
				},
			},
		},
	})
}
