// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoRestrictedExportsRule(t *testing.T) {
	RunRuleTester(t, "{\"languageOptions\":{\"ecmaVersion\":2022,\"sourceType\":\"module\"}}", "no-restricted-exports", []ValidTestCase{
		{Code: `export var a;`},
		{Code: `export function a() {}`},
		{Code: `export class A {}`},
		{Code: `var a; export { a };`},
		{Code: `var b; export { b as a };`},
		{Code: `export { a } from 'foo';`},
		{Code: `export { b as a } from 'foo';`},
		{
			Code:    `export var a;`,
			Options: "[{}]",
		},
		{
			Code:    `export function a() {}`,
			Options: "[{}]",
		},
		{
			Code:    `export class A {}`,
			Options: "[{}]",
		},
		{
			Code:    `var a; export { a };`,
			Options: "[{}]",
		},
		{
			Code:    `var b; export { b as a };`,
			Options: "[{}]",
		},
		{
			Code:    `export { a } from 'foo';`,
			Options: "[{}]",
		},
		{
			Code:    `export { b as a } from 'foo';`,
			Options: "[{}]",
		},
		{
			Code:    `export var a;`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `export function a() {}`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `export class A {}`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `var a; export { a };`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `var b; export { b as a };`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `export { a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `export { b as a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[]}]",
		},
		{
			Code:    `export var a;`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export let a;`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export const a = 1;`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export function a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export function *a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export async function a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export async function *a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export class A {}`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `var a; export { a };`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `var b; export { b as a };`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export { a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export { b as a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"x\"]}]",
		},
		{
			Code:    `export { '' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"undefined\"]}]",
		},
		{
			Code:    `export { '' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\" \"]}]",
		},
		{
			Code:    `export { ' ' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"\"]}]",
		},
		{
			Code:    `export { ' a', 'a ' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export var b = a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export let [b = a] = [];`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export const [b] = [a];`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export var { a: b } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export let { b = a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export const { c: b = a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export function b(a) {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export class A { a(){} }`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export class A extends B {}`,
			Options: "[{\"restrictedNamedExports\":[\"B\"]}]",
		},
		{
			Code:    `var a; export { a as b };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `var a; export { a as 'a ' };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export { a as b } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export { a as 'a ' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export { 'a' as 'a ' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export { b } from 'a';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export * as b from 'a';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `var a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `let a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `const a = 1;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `function a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `class A {}`,
			Options: "[{\"restrictedNamedExports\":[\"A\"]}]",
		},
		{
			Code:    `import a from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `import { a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `import { b as a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `var setSomething; export { setSomething };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"^get\"}]",
		},
		{
			Code:    `var foo, bar; export { foo, bar };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"^(?!foo)(?!bar).+$\"}]",
		},
		{
			Code:    `var foobar; export default foobar;`,
			Options: "[{\"restrictedNamedExportsPattern\":\"bar$\"}]",
		},
		{
			Code:    `var foobar; export default foobar;`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `export default 'default';`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `var foobar; export { foobar as default };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `var foobar; export { foobar as 'default' };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `export { default } from 'mod';`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `export { default as default } from 'mod';`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `export { foobar as default } from 'mod';`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `export * as default from 'mod';`,
			Options: "[{\"restrictedNamedExportsPattern\":\"default\"}]",
		},
		{
			Code:    `export * from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export * from 'a';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export default a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export default function a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export default class A {}`,
			Options: "[{\"restrictedNamedExports\":[\"A\"]}]",
		},
		{
			Code:    `export default (function a() {});`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
		},
		{
			Code:    `export default (class A {});`,
			Options: "[{\"restrictedNamedExports\":[\"A\"]}]",
		},
		{
			Code:    `export default 1;`,
			Options: "[{\"restrictedNamedExports\":[\"default\"]}]",
		},
		{
			Code:    `export { default as a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"default\"]}]",
		},
		{
			Code:    `export default foo;`,
			Options: "[{\"restrictDefaultExports\":{\"direct\":false}}]",
		},
		{
			Code:    `export default 42;`,
			Options: "[{\"restrictDefaultExports\":{\"direct\":false}}]",
		},
		{
			Code:    `export default function foo() {}`,
			Options: "[{\"restrictDefaultExports\":{\"direct\":false}}]",
		},
		{
			Code: `const foo = 123;
export { foo as default };`,
			Options: "[{\"restrictDefaultExports\":{\"named\":false}}]",
		},
		{
			Code:    `export { default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":false}}]",
		},
		{
			Code:    `export { default as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":false}}]",
		},
		{
			Code:    `export { foo as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":true}}]",
		},
		{
			Code:    `export { default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"named\":true,\"defaultFrom\":false}}]",
		},
		{
			Code:    `export { 'default' } from 'mod'; `,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":false}}]",
		},
		{
			Code:    `export { foo as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"namedFrom\":false}}]",
		},
		{
			Code:    `export { default as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"namedFrom\":true}}]",
		},
		{
			Code:    `export { default as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"namedFrom\":false}}]",
		},
		{
			Code:    `export { 'default' } from 'mod'; `,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":false,\"namedFrom\":true}}]",
		},
		{
			Code:    `export * as default from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"namespaceFrom\":false}}]",
		},
	}, []InvalidTestCase{
		{
			Code:    `export function someFunction() {}`,
			Options: "[{\"restrictedNamedExports\":[\"someFunction\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export var a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export var a = 1;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export let a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export let a = 1;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export const a = 1;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export function a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export function *a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export async function a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export async function *a() {}`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export class A {}`,
			Options: "[{\"restrictedNamedExports\":[\"A\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `let a; export { a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    17,
				},
			},
		},
		{
			Code:    `export { a }; var a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    10,
				},
			},
		},
		{
			Code:    `let b; export { b as a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { b as a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `let a; export { a as 'a' };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    22,
				},
			},
		},
		{
			Code:    `let a; export { a as 'b' };`,
			Options: "[{\"restrictedNamedExports\":[\"b\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    22,
				},
			},
		},
		{
			Code:    `let a; export { a as ' b ' };`,
			Options: "[{\"restrictedNamedExports\":[\" b \"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    22,
				},
			},
		},
		{
			Code:    `let a; export { a as '👍' };`,
			Options: "[{\"restrictedNamedExports\":[\"👍\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    22,
				},
			},
		},
		{
			Code:    `export { 'a' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { '' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { ' ' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\" \"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { b as 'a' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { b as '\u0061' } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export * as 'a' from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export var [a] = [];`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export let { a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export const { b: a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export var [{ a }] = [];`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export let { b: { c: a = d } = e } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var a; export var a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    19,
				},
			},
		},
		{
			Code:    `export var a; var a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    12,
				},
			},
		},
		{
			Code:    `export var a = a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    12,
				},
			},
		},
		{
			Code:    `export let b = a, a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    19,
				},
			},
		},
		{
			Code:    `export const a = 1, b = a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    14,
				},
			},
		},
		{
			Code:    `export var [a] = a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    13,
				},
			},
		},
		{
			Code:    `export let { a: a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    17,
				},
			},
		},
		{
			Code:    `export const { a: b, b: a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    25,
				},
			},
		},
		{
			Code:    `export var { b: a, a: b } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    17,
				},
			},
		},
		{
			Code:    `export let a, { a: b } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    12,
				},
			},
		},
		{
			Code:    `export const { a: b } = {}, a = 1;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    29,
				},
			},
		},
		{
			Code:    `export var [a = a] = [];`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    13,
				},
			},
		},
		{
			Code:    `export var { a: a = a } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    17,
				},
			},
		},
		{
			Code:    `export let { a } = { a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    14,
				},
			},
		},
		{
			Code:    `export function a(a) {};`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    17,
				},
			},
		},
		{
			Code:    `export class A { A(){} };`,
			Options: "[{\"restrictedNamedExports\":[\"A\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    14,
				},
			},
		},
		{
			Code:    `var a; export { a as a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    22,
				},
			},
		},
		{
			Code:    `let a, b; export { a as b, b as a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    33,
				},
			},
		},
		{
			Code:    `const a = 1, b = 2; export { b as a, a as b };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    35,
				},
			},
		},
		{
			Code:    `var a; export { a as b, a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    25,
				},
			},
		},
		{
			Code:    `export { a as a } from 'a';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    15,
				},
			},
		},
		{
			Code:    `export { a as b, b as a } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    23,
				},
			},
		},
		{
			Code:    `export { b as a, a as b } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    15,
				},
			},
		},
		{
			Code:    `export * as a from 'a';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    13,
				},
			},
		},
		{
			Code:    `export var a, b;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export let b, a;`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export const b = 1, a = 2;`,
			Options: "[{\"restrictedNamedExports\":[\"a\",\"b\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export var a, b, c;`,
			Options: "[{\"restrictedNamedExports\":[\"a\",\"c\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export let { a, b, c } = {};`,
			Options: "[{\"restrictedNamedExports\":[\"b\",\"c\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export const [a, b, c, d] = {};`,
			Options: "[{\"restrictedNamedExports\":[\"b\",\"c\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export var { a, x: b, c, d, e: y } = {}, e, f = {};`,
			Options: "[{\"restrictedNamedExports\":[\"foo\",\"a\",\"b\",\"bar\",\"d\",\"e\",\"baz\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
					Column:    42,
				},
			},
		},
		{
			Code:    `var a, b; export { a, b };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `let a, b; export { b, a };`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `const a = 1, b = 1; export { a, b };`,
			Options: "[{\"restrictedNamedExports\":[\"a\",\"b\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { a, b, c }; var a, b, c;`,
			Options: "[{\"restrictedNamedExports\":[\"a\",\"c\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { b as a, b } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export { b as a, b } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"b\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    18,
				},
			},
		},
		{
			Code:    `export { b as a, b } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"a\",\"b\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
					Column:    18,
				},
			},
		},
		{
			Code:    `export { a, b, c, d, x as e, f, g } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"foo\",\"b\",\"bar\",\"d\",\"e\",\"f\",\"baz\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var getSomething; export { getSomething };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"get*\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var getSomethingFromUser; export { getSomethingFromUser };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"User$\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var foo, ab, xy; export { foo, ab, xy };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"(b|y)$\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var foo; export { foo as ab };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"(b|y)$\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var privateUserEmail; export { privateUserEmail };`,
			Options: "[{\"restrictedNamedExportsPattern\":\"^privateUser\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `export const a = 1;`,
			Options: "[{\"restrictedNamedExportsPattern\":\"^(?!foo)(?!bar).+$\"}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
				},
			},
		},
		{
			Code:    `var a; export { a as default };`,
			Options: "[{\"restrictedNamedExports\":[\"default\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    22,
				},
			},
		},
		{
			Code:    `export { default } from 'foo';`,
			Options: "[{\"restrictedNamedExports\":[\"default\"]}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedNamed",
					Column:    10,
				},
			},
		},
		{
			Code:    `export default foo;`,
			Options: "[{\"restrictDefaultExports\":{\"direct\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Column:    1,
				},
			},
		},
		{
			Code:    `export default 42;`,
			Options: "[{\"restrictDefaultExports\":{\"direct\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Column:    1,
				},
			},
		},
		{
			Code:    `export default function foo() {}`,
			Options: "[{\"restrictDefaultExports\":{\"direct\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Column:    1,
				},
			},
		},
		{
			Code:    `export default foo;`,
			Options: "[{\"restrictedNamedExports\":[\"bar\"],\"restrictDefaultExports\":{\"direct\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Column:    1,
				},
			},
		},
		{
			Code: `const foo = 123;
export { foo as default };`,
			Options: "[{\"restrictDefaultExports\":{\"named\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Line:      2,
					Column:    17,
				},
			},
		},
		{
			Code:    `export { default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Line:      1,
					Column:    10,
				},
			},
		},
		{
			Code:    `export { default as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Line:      1,
					Column:    21,
				},
			},
		},
		{
			Code:    `export { 'default' } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"defaultFrom\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Line:      1,
					Column:    10,
				},
			},
		},
		{
			Code:    `export { foo as default } from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"namedFrom\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Line:      1,
					Column:    17,
				},
			},
		},
		{
			Code:    `export * as default from 'mod';`,
			Options: "[{\"restrictDefaultExports\":{\"namespaceFrom\":true}}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "restrictedDefault",
					Line:      1,
					Column:    13,
				},
			},
		},
	})
}
