// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestNoSyncRule(t *testing.T) {
	RunRuleTester(t, "{}", "no-sync", []ValidTestCase{
		{Code: `var foo = fs.foo.foo();`},
		{
			Code:    `var foo = fs.fooSync;`,
			Options: "[{\"allowAtRootLevel\":true}]",
		},
		{
			Code:    `if (true) {fs.fooSync();}`,
			Options: "[{\"allowAtRootLevel\":true}]",
		},
	}, []InvalidTestCase{
		{
			Code: `var foo = fs.fooSync();`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
		{
			Code:    `var foo = fs.fooSync();`,
			Options: "[{\"allowAtRootLevel\":false}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
		{
			Code: `if (true) {fs.fooSync();}`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
		{
			Code: `var foo = fs.fooSync;`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
		{
			Code: `function someFunction() {fs.fooSync();}`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
		{
			Code:    `function someFunction() {fs.fooSync();}`,
			Options: "[{\"allowAtRootLevel\":true}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
		{
			Code:    `var a = function someFunction() {fs.fooSync();}`,
			Options: "[{\"allowAtRootLevel\":true}]",
			Errors: []InvalidTestCaseError{
				{
					MessageId: "noSync",
				},
			},
		},
	})
}
