// Code generated by gen-eslint-core-rule-tests.ts. DO NOT EDIT.

package core_rule_tests

import (
	"testing"
)

func TestRequireYieldRule(t *testing.T) {
	RunRuleTester(t, "{\"languageOptions\":{\"ecmaVersion\":6}}", "require-yield", []ValidTestCase{
		{Code: `function foo() { return 0; }`},
		{Code: `function* foo() { yield 0; }`},
		{Code: `function* foo() { }`},
		{Code: `(function* foo() { yield 0; })();`},
		{Code: `(function* foo() { })();`},
		{Code: `var obj = { *foo() { yield 0; } };`},
		{Code: `var obj = { *foo() { } };`},
		{Code: `class A { *foo() { yield 0; } };`},
		{Code: `class A { *foo() { } };`},
	}, []InvalidTestCase{
		{
			Code: `function* foo() { return 0; }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingYield",
				},
			},
		},
		{
			Code: `(function* foo() { return 0; })();`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingYield",
				},
			},
		},
		{
			Code: `var obj = { *foo() { return 0; } }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingYield",
				},
			},
		},
		{
			Code: `class A { *foo() { return 0; } }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingYield",
				},
			},
		},
		{
			Code: `function* foo() { function* bar() { yield 0; } }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingYield",
					Column:    1,
				},
			},
		},
		{
			Code: `function* foo() { function* bar() { return 0; } yield 0; }`,
			Errors: []InvalidTestCaseError{
				{
					MessageId: "missingYield",
					Column:    19,
				},
			},
		},
	})
}
