package estree

//go:generate node --run tools:gen-estree-ast

type ESTreeKind = string

const (
	ESTreeKindAccessorProperty                ESTreeKind = "AccessorProperty"
	ESTreeKindArrayExpression                 ESTreeKind = "ArrayExpression"
	ESTreeKindArrayPattern                    ESTreeKind = "ArrayPattern"
	ESTreeKindArrowFunctionExpression         ESTreeKind = "ArrowFunctionExpression"
	ESTreeKindAssignmentExpression            ESTreeKind = "AssignmentExpression"
	ESTreeKindAssignmentPattern               ESTreeKind = "AssignmentPattern"
	ESTreeKindAwaitExpression                 ESTreeKind = "AwaitExpression"
	ESTreeKindBinaryExpression                ESTreeKind = "BinaryExpression"
	ESTreeKindBlockStatement                  ESTreeKind = "BlockStatement"
	ESTreeKindBreakStatement                  ESTreeKind = "BreakStatement"
	ESTreeKindCallExpression                  ESTreeKind = "CallExpression"
	ESTreeKindCatchClause                     ESTreeKind = "CatchClause"
	ESTreeKindChainExpression                 ESTreeKind = "ChainExpression"
	ESTreeKindClassBody                       ESTreeKind = "ClassBody"
	ESTreeKindClassDeclaration                ESTreeKind = "ClassDeclaration"
	ESTreeKindClassExpression                 ESTreeKind = "ClassExpression"
	ESTreeKindConditionalExpression           ESTreeKind = "ConditionalExpression"
	ESTreeKindContinueStatement               ESTreeKind = "ContinueStatement"
	ESTreeKindDebuggerStatement               ESTreeKind = "DebuggerStatement"
	ESTreeKindDecorator                       ESTreeKind = "Decorator"
	ESTreeKindDoWhileStatement                ESTreeKind = "DoWhileStatement"
	ESTreeKindEmptyStatement                  ESTreeKind = "EmptyStatement"
	ESTreeKindExportAllDeclaration            ESTreeKind = "ExportAllDeclaration"
	ESTreeKindExportDefaultDeclaration        ESTreeKind = "ExportDefaultDeclaration"
	ESTreeKindExportNamedDeclaration          ESTreeKind = "ExportNamedDeclaration"
	ESTreeKindExportSpecifier                 ESTreeKind = "ExportSpecifier"
	ESTreeKindExpressionStatement             ESTreeKind = "ExpressionStatement"
	ESTreeKindForInStatement                  ESTreeKind = "ForInStatement"
	ESTreeKindForOfStatement                  ESTreeKind = "ForOfStatement"
	ESTreeKindForStatement                    ESTreeKind = "ForStatement"
	ESTreeKindFunctionDeclaration             ESTreeKind = "FunctionDeclaration"
	ESTreeKindFunctionExpression              ESTreeKind = "FunctionExpression"
	ESTreeKindIdentifier                      ESTreeKind = "Identifier"
	ESTreeKindIfStatement                     ESTreeKind = "IfStatement"
	ESTreeKindImportAttribute                 ESTreeKind = "ImportAttribute"
	ESTreeKindImportDeclaration               ESTreeKind = "ImportDeclaration"
	ESTreeKindImportDefaultSpecifier          ESTreeKind = "ImportDefaultSpecifier"
	ESTreeKindImportExpression                ESTreeKind = "ImportExpression"
	ESTreeKindImportNamespaceSpecifier        ESTreeKind = "ImportNamespaceSpecifier"
	ESTreeKindImportSpecifier                 ESTreeKind = "ImportSpecifier"
	ESTreeKindJSXAttribute                    ESTreeKind = "JSXAttribute"
	ESTreeKindJSXClosingElement               ESTreeKind = "JSXClosingElement"
	ESTreeKindJSXClosingFragment              ESTreeKind = "JSXClosingFragment"
	ESTreeKindJSXElement                      ESTreeKind = "JSXElement"
	ESTreeKindJSXEmptyExpression              ESTreeKind = "JSXEmptyExpression"
	ESTreeKindJSXExpressionContainer          ESTreeKind = "JSXExpressionContainer"
	ESTreeKindJSXFragment                     ESTreeKind = "JSXFragment"
	ESTreeKindJSXIdentifier                   ESTreeKind = "JSXIdentifier"
	ESTreeKindJSXMemberExpression             ESTreeKind = "JSXMemberExpression"
	ESTreeKindJSXNamespacedName               ESTreeKind = "JSXNamespacedName"
	ESTreeKindJSXOpeningElement               ESTreeKind = "JSXOpeningElement"
	ESTreeKindJSXOpeningFragment              ESTreeKind = "JSXOpeningFragment"
	ESTreeKindJSXSpreadAttribute              ESTreeKind = "JSXSpreadAttribute"
	ESTreeKindJSXSpreadChild                  ESTreeKind = "JSXSpreadChild"
	ESTreeKindJSXText                         ESTreeKind = "JSXText"
	ESTreeKindLabeledStatement                ESTreeKind = "LabeledStatement"
	ESTreeKindLiteral                         ESTreeKind = "Literal"
	ESTreeKindLogicalExpression               ESTreeKind = "LogicalExpression"
	ESTreeKindMemberExpression                ESTreeKind = "MemberExpression"
	ESTreeKindMetaProperty                    ESTreeKind = "MetaProperty"
	ESTreeKindMethodDefinition                ESTreeKind = "MethodDefinition"
	ESTreeKindNewExpression                   ESTreeKind = "NewExpression"
	ESTreeKindObjectExpression                ESTreeKind = "ObjectExpression"
	ESTreeKindObjectPattern                   ESTreeKind = "ObjectPattern"
	ESTreeKindPrivateIdentifier               ESTreeKind = "PrivateIdentifier"
	ESTreeKindProgram                         ESTreeKind = "Program"
	ESTreeKindProperty                        ESTreeKind = "Property"
	ESTreeKindPropertyDefinition              ESTreeKind = "PropertyDefinition"
	ESTreeKindRestElement                     ESTreeKind = "RestElement"
	ESTreeKindReturnStatement                 ESTreeKind = "ReturnStatement"
	ESTreeKindSequenceExpression              ESTreeKind = "SequenceExpression"
	ESTreeKindSpreadElement                   ESTreeKind = "SpreadElement"
	ESTreeKindStaticBlock                     ESTreeKind = "StaticBlock"
	ESTreeKindSuper                           ESTreeKind = "Super"
	ESTreeKindSwitchCase                      ESTreeKind = "SwitchCase"
	ESTreeKindSwitchStatement                 ESTreeKind = "SwitchStatement"
	ESTreeKindTaggedTemplateExpression        ESTreeKind = "TaggedTemplateExpression"
	ESTreeKindTemplateElement                 ESTreeKind = "TemplateElement"
	ESTreeKindTemplateLiteral                 ESTreeKind = "TemplateLiteral"
	ESTreeKindThisExpression                  ESTreeKind = "ThisExpression"
	ESTreeKindThrowStatement                  ESTreeKind = "ThrowStatement"
	ESTreeKindTryStatement                    ESTreeKind = "TryStatement"
	ESTreeKindUnaryExpression                 ESTreeKind = "UnaryExpression"
	ESTreeKindUpdateExpression                ESTreeKind = "UpdateExpression"
	ESTreeKindVariableDeclaration             ESTreeKind = "VariableDeclaration"
	ESTreeKindVariableDeclarator              ESTreeKind = "VariableDeclarator"
	ESTreeKindWhileStatement                  ESTreeKind = "WhileStatement"
	ESTreeKindWithStatement                   ESTreeKind = "WithStatement"
	ESTreeKindYieldExpression                 ESTreeKind = "YieldExpression"
	ESTreeKindTSAbstractAccessorProperty      ESTreeKind = "TSAbstractAccessorProperty"
	ESTreeKindTSAbstractKeyword               ESTreeKind = "TSAbstractKeyword"
	ESTreeKindTSAbstractMethodDefinition      ESTreeKind = "TSAbstractMethodDefinition"
	ESTreeKindTSAbstractPropertyDefinition    ESTreeKind = "TSAbstractPropertyDefinition"
	ESTreeKindTSAnyKeyword                    ESTreeKind = "TSAnyKeyword"
	ESTreeKindTSArrayType                     ESTreeKind = "TSArrayType"
	ESTreeKindTSAsExpression                  ESTreeKind = "TSAsExpression"
	ESTreeKindTSAsyncKeyword                  ESTreeKind = "TSAsyncKeyword"
	ESTreeKindTSBigIntKeyword                 ESTreeKind = "TSBigIntKeyword"
	ESTreeKindTSBooleanKeyword                ESTreeKind = "TSBooleanKeyword"
	ESTreeKindTSCallSignatureDeclaration      ESTreeKind = "TSCallSignatureDeclaration"
	ESTreeKindTSClassImplements               ESTreeKind = "TSClassImplements"
	ESTreeKindTSConditionalType               ESTreeKind = "TSConditionalType"
	ESTreeKindTSConstructorType               ESTreeKind = "TSConstructorType"
	ESTreeKindTSConstructSignatureDeclaration ESTreeKind = "TSConstructSignatureDeclaration"
	ESTreeKindTSDeclareFunction               ESTreeKind = "TSDeclareFunction"
	ESTreeKindTSDeclareKeyword                ESTreeKind = "TSDeclareKeyword"
	ESTreeKindTSEmptyBodyFunctionExpression   ESTreeKind = "TSEmptyBodyFunctionExpression"
	ESTreeKindTSEnumBody                      ESTreeKind = "TSEnumBody"
	ESTreeKindTSEnumDeclaration               ESTreeKind = "TSEnumDeclaration"
	ESTreeKindTSEnumMember                    ESTreeKind = "TSEnumMember"
	ESTreeKindTSExportAssignment              ESTreeKind = "TSExportAssignment"
	ESTreeKindTSExportKeyword                 ESTreeKind = "TSExportKeyword"
	ESTreeKindTSExternalModuleReference       ESTreeKind = "TSExternalModuleReference"
	ESTreeKindTSFunctionType                  ESTreeKind = "TSFunctionType"
	ESTreeKindTSImportEqualsDeclaration       ESTreeKind = "TSImportEqualsDeclaration"
	ESTreeKindTSImportType                    ESTreeKind = "TSImportType"
	ESTreeKindTSIndexedAccessType             ESTreeKind = "TSIndexedAccessType"
	ESTreeKindTSIndexSignature                ESTreeKind = "TSIndexSignature"
	ESTreeKindTSInferType                     ESTreeKind = "TSInferType"
	ESTreeKindTSInstantiationExpression       ESTreeKind = "TSInstantiationExpression"
	ESTreeKindTSInterfaceBody                 ESTreeKind = "TSInterfaceBody"
	ESTreeKindTSInterfaceDeclaration          ESTreeKind = "TSInterfaceDeclaration"
	ESTreeKindTSInterfaceHeritage             ESTreeKind = "TSInterfaceHeritage"
	ESTreeKindTSIntersectionType              ESTreeKind = "TSIntersectionType"
	ESTreeKindTSIntrinsicKeyword              ESTreeKind = "TSIntrinsicKeyword"
	ESTreeKindTSLiteralType                   ESTreeKind = "TSLiteralType"
	ESTreeKindTSMappedType                    ESTreeKind = "TSMappedType"
	ESTreeKindTSMethodSignature               ESTreeKind = "TSMethodSignature"
	ESTreeKindTSModuleBlock                   ESTreeKind = "TSModuleBlock"
	ESTreeKindTSModuleDeclaration             ESTreeKind = "TSModuleDeclaration"
	ESTreeKindTSNamedTupleMember              ESTreeKind = "TSNamedTupleMember"
	ESTreeKindTSNamespaceExportDeclaration    ESTreeKind = "TSNamespaceExportDeclaration"
	ESTreeKindTSNeverKeyword                  ESTreeKind = "TSNeverKeyword"
	ESTreeKindTSNonNullExpression             ESTreeKind = "TSNonNullExpression"
	ESTreeKindTSNullKeyword                   ESTreeKind = "TSNullKeyword"
	ESTreeKindTSNumberKeyword                 ESTreeKind = "TSNumberKeyword"
	ESTreeKindTSObjectKeyword                 ESTreeKind = "TSObjectKeyword"
	ESTreeKindTSOptionalType                  ESTreeKind = "TSOptionalType"
	ESTreeKindTSParameterProperty             ESTreeKind = "TSParameterProperty"
	ESTreeKindTSPrivateKeyword                ESTreeKind = "TSPrivateKeyword"
	ESTreeKindTSPropertySignature             ESTreeKind = "TSPropertySignature"
	ESTreeKindTSProtectedKeyword              ESTreeKind = "TSProtectedKeyword"
	ESTreeKindTSPublicKeyword                 ESTreeKind = "TSPublicKeyword"
	ESTreeKindTSQualifiedName                 ESTreeKind = "TSQualifiedName"
	ESTreeKindTSReadonlyKeyword               ESTreeKind = "TSReadonlyKeyword"
	ESTreeKindTSRestType                      ESTreeKind = "TSRestType"
	ESTreeKindTSSatisfiesExpression           ESTreeKind = "TSSatisfiesExpression"
	ESTreeKindTSStaticKeyword                 ESTreeKind = "TSStaticKeyword"
	ESTreeKindTSStringKeyword                 ESTreeKind = "TSStringKeyword"
	ESTreeKindTSSymbolKeyword                 ESTreeKind = "TSSymbolKeyword"
	ESTreeKindTSTemplateLiteralType           ESTreeKind = "TSTemplateLiteralType"
	ESTreeKindTSThisType                      ESTreeKind = "TSThisType"
	ESTreeKindTSTupleType                     ESTreeKind = "TSTupleType"
	ESTreeKindTSTypeAliasDeclaration          ESTreeKind = "TSTypeAliasDeclaration"
	ESTreeKindTSTypeAnnotation                ESTreeKind = "TSTypeAnnotation"
	ESTreeKindTSTypeAssertion                 ESTreeKind = "TSTypeAssertion"
	ESTreeKindTSTypeLiteral                   ESTreeKind = "TSTypeLiteral"
	ESTreeKindTSTypeOperator                  ESTreeKind = "TSTypeOperator"
	ESTreeKindTSTypeParameter                 ESTreeKind = "TSTypeParameter"
	ESTreeKindTSTypeParameterDeclaration      ESTreeKind = "TSTypeParameterDeclaration"
	ESTreeKindTSTypeParameterInstantiation    ESTreeKind = "TSTypeParameterInstantiation"
	ESTreeKindTSTypePredicate                 ESTreeKind = "TSTypePredicate"
	ESTreeKindTSTypeQuery                     ESTreeKind = "TSTypeQuery"
	ESTreeKindTSTypeReference                 ESTreeKind = "TSTypeReference"
	ESTreeKindTSUndefinedKeyword              ESTreeKind = "TSUndefinedKeyword"
	ESTreeKindTSUnionType                     ESTreeKind = "TSUnionType"
	ESTreeKindTSUnknownKeyword                ESTreeKind = "TSUnknownKeyword"
	ESTreeKindTSVoidKeyword                   ESTreeKind = "TSVoidKeyword"
)

const (
	ESTreeTokenTypeBoolean           ESTreeKind = "Boolean"
	ESTreeTokenTypeIdentifier        ESTreeKind = "Identifier"
	ESTreeTokenTypeJSXIdentifier     ESTreeKind = "JSXIdentifier"
	ESTreeTokenTypePrivateIdentifier ESTreeKind = "PrivateIdentifier"
	ESTreeTokenTypeJSXText           ESTreeKind = "JSXText"
	ESTreeTokenTypeKeyword           ESTreeKind = "Keyword"
	ESTreeTokenTypeNull              ESTreeKind = "Null"
	ESTreeTokenTypeNumeric           ESTreeKind = "Numeric"
	ESTreeTokenTypePunctuator        ESTreeKind = "Punctuator"
	ESTreeTokenTypeRegularExpression ESTreeKind = "RegularExpression"
	ESTreeTokenTypeString            ESTreeKind = "String"
	ESTreeTokenTypeTemplate          ESTreeKind = "Template"
	ESTreeTokenTypeBlock             ESTreeKind = "Block"
	ESTreeTokenTypeLine              ESTreeKind = "Line"

	ESTreeTokenTypeShebang ESTreeKind = "Shebang"
)

type Position struct {
	Column int
	Line   int
}

type SourceLocation struct {
	End   Position
	Start Position
}

type Range [2]int

type NodeWithRange interface {
	GetType() ESTreeKind
	GetRange() Range
	setRange(r Range)
	GetLoc() SourceLocation
	setLoc(l SourceLocation)
	SetParent(parent NodeWithRange)
}
